name: build-linux
on: [push]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run:  |
              sudo apt-get install python3-dev gcc cmake
              sudo apt-get update -y || true &&  DEBIAN_FRONTEND=noninteractive sudo apt-get install -y tzdata libx11-dev && sudo apt-get install -y --no-install-recommends libopencv-dev
              mkdir bin
              cd bin
              cmake ../.
              make
        name: upload_artifact
      - uses: actions/upload-artifact@v4
        with:
          name: artifact-linux-build
          path: |
                  bin
          retention-days: 1

  cpp-plate-solving-witch-head:
    runs-on: ubuntu-latest
    needs: [build-linux]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: |
            mkdir bin
            sudo apt-get update -y || true &&  DEBIAN_FRONTEND=noninteractive sudo apt-get install -y tzdata libx11-dev && sudo apt-get install -y --no-install-recommends libopencv-dev
      - uses: actions/download-artifact@v4
        with:
          name: artifact-linux-build
          path: bin/.
      - run:  |
              chmod u+x bin/plate_solve
              ./bin/plate_solve plate_solver_test_files/data/index_file_200mm.kdtree plate_solver_test_files/data/catalogue.bin plate_solver_test_files/data/photos/witch_head_small_200mm.jpg
        name: plate-solve


  python-plate-solve-and-compare-witch-head:
    runs-on: ubuntu-latest
    needs: [build-linux]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: |
            mkdir bin
            sudo apt-get update -y || true &&  DEBIAN_FRONTEND=noninteractive sudo apt-get install -y tzdata libx11-dev && sudo apt-get install -y --no-install-recommends libopencv-dev
      - uses: actions/download-artifact@v4
        with:
          name: artifact-linux-build
          path: bin/.
      - run:  |
              cd CI_tests/
              python3 python/test_plate_solving.py ../plate_solver_test_files/data/catalogue.bin ../plate_solver_test_files/data/index_file_200mm.kdtree ../plate_solver_test_files/data/photos/witch_head_small_200mm.jpg 5.091,-9.264,-90.869,10.34,6.9
        name: plate-solve